[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/l68CQ2vgQW7t5BiyiPAdC-rhTcGy_9xZ"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "${scan_endpoints.sepoliascan}", chain = "sepolia"}

[profile.scan_endpoints]
sepolia = "https://api-sepolia.etherscan.io/api"